services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=Hobist
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '5432:5432'
    volumes:
      - uploads:/media

volumes:
  uploads: