version: '3.9'
services:
  postgres:
    image: 'postgres:16'
    container_name: postgres-db
    environment:
      - POSTGRES_DB=Hobist
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '5432:5432'
#   volumes:
#      - db_data:/var/lib/postgresql/data

