services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=Hobist
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '5432:5432'
#    volumes: M.G:not in use for now
#      - ./uploads:/media
