version: "3.9"

services:
  postgres:
    image: "postgres:16"
    container_name: hobist-postgres
    environment:
      POSTGRES_DB: Hobist
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - hobist_db_data:/var/lib/postgresql/data

volumes:
  hobist_db_data:
